---
- hosts: test-it
  vars:
  - name: "Yakir"

  tasks:
  - name: Update the repository cache and update package "curl" to latest version
    apt:
      name: curl
      state: latest  
      update_cache: no
    
   - name: Print message
     debug: msg="Hello to {{name}}, from Ansible!!"
